### PR TITLE
Revert "Bootstrap master"

### PR DESCRIPTION
**Pull request by austinkregel**
Reverts austinkregel/php-login-advanced#12

### CODE REVIEW

**Comment by Wargog** [comment]
Why did you revert the PR?

**Comment by austinkregel** [comment]
It had some errors in it.

**Comment by austinkregel** [comment]
You seem to be well versed with git... I'm not that familiar with git. I have the up to date repo on my server, but I don't know how to merge my current repo with one of the other branches. (mainly the bugfixes branch or the master). Every time I try to push the repo it always puts in the file something like `<<<<<<<<< HEADER`

**Comment by Wargog** [comment]
Um, I have only reverted a series of commits before, I don't really use this whole pull request system, I'm used something like `git cherrypick` or `git revert [SHA]` and it didn't put the <<<<<<<< HEAD in all my files, I'm not sure why it's doing that to you honestly.

**Pull request merged**
