### PR TITLE
Should be all that's needed for custom configs

### LINKED ISSUE #8: Custom config location
Would there be any way to make something that allows the user to set a custom location for the config, so if they would like to make a universal config for their project that includes the values for php-login as well as their scripts.

### PR DESCRIPTION
**Pull request by Wargog**
If I'm right, this will only load one of the configs, with the default being loaded if one is specified. Also, changed registerNewUser to public to allow registration from outside of the main class.
- Closes #8
# Usage

When calling the class, simply use a parameter `$login = new PHPLogin(dirname(__DIR__) . '/config.php');`

### CODE REVIEW

**Comment by austinkregel** [comment]
I will review these changes over this upcoming weekend and I will make the changes accordingly. I quickly looked them over and the only thing I'd like to know about is why would you want to register users outside of the main class? I assume it's to override some implementation that the script currently has. 
(I don't have an issue with it, just looking for your opinion on it)

**Comment by Wargog** [comment]
Well, if you want to use a custom registration form, or not use one at all, such as in my project when I show the install form it is supposed to use the config it creates, create the login object and register the user using this form: http://gyazo.com/dec8cea4db79d09b8dac6dd51d65b8b6

**Comment by austinkregel** [comment]
Oh okay, I could see how that would be useful. I'll make the changes sometime this weekend and I'll do my best to test it extensively.

**Comment by Wargog** [comment]
Any progress?

**Comment by austinkregel** [comment]
Did you test your build before you submitted the merge? I have been testing your build but it doesn't work.

**Comment by Wargog** [comment]
Well what I was going for was possibly using another method to set the
variable for the directory but then it would need to be called every time
you create a new instance

**Comment by austinkregel** [comment]
I am currently brewing up a method as we speak. You can see it in the branch "dev-bugfixes".

**Comment by Wargog** [comment]
I see the commits, your method is a lot better than mine haha, as long as I can just use my own I'll be happy

**Comment by austinkregel** [comment]
You can totally use your own config. Best part is you can select and choose which values you want changed.

**Comment by austinkregel** [comment]
I just got done testing everything. It looks good, and everything seems to work well. I am proud to say that there is now the option of a customised config. I will be merging my commit soon.

**Comment by Wargog** [comment]
Awesome, thank you

**Comment by Wargog** [comment]
Any ETA on the changes being pushed to bootstrap?

**Pull request closed without merging**
