### PR TITLE
Small fixes - Bootstrap

### PR DESCRIPTION
**Pull request by Zer0xFF**
I'd imagine the 2nd commit would also apply to the remaining branches.

I'd also like to mention a small issue with https://github.com/Thunder07/php-login-advanced/blob/bootstrap-patch/classes/PHPLogin.php#L443 on rare occasions you can get 'Undefined index: user_id', probably due to the loss of php session cookies, this seems to be fixed by using the variable  $user_id ,which might have been the original intent to start with, but since this is a rare happening, it's hard to find the actual trigger point to test this, I've only been able to replicate this once.

### CODE REVIEW

**Comment by austinkregel** [comment]
I'm not going to merge this; however, I will change these in each branch..

**Comment by Zer0xFF** [comment]
That works for me :)

**Comment by austinkregel** [comment]
Okay :) I'll be pushing it as soon as I can check it all out and submit the changes.

**Comment by austinkregel** [comment]
@Thunder07 I think I was able to get them all :)

**Comment by Zer0xFF** [comment]
Cool, just for the user_index issue, instead of skipping the bind with an if condition, you should really skip the entire statement, as in, the condition should be checked further up here https://github.com/austinkregel/php-login-advanced/commit/e57b6fc2d018bfb775472ed880729f1c5f1c152a#diff-21720befd37585509aaa57426b38b213R438

**Comment by austinkregel** [comment]
There we go :) Thank you @Thunder07

**Comment by Zer0xFF** [comment]
Glad to be of help :)

**Pull request closed without merging**
